export enum FormActionType {
    CREATE_FILE = "createFile",
    INSERT_TEXT = "insertText",
    RUN_SCRIPT = "runScript",
    UPDATE_FRONTMATTER = "updateFrontmatter",
    SUGGEST_MODAL = "suggestModal",
    GENERATE_FORM = "generateForm",
    RUN_COMMAND = "runCommand",
    WAIT = "wait",
    BUTTON = "button",
    TEXT = "text",
    AI = "ai",
    LOOP = "loop",
    BREAK = "break",
    CONTINUE = "continue",
}
