import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Obsidian 插件目标目录
const OBSIDIAN_PLUGIN_DIR = "C:\\Desktop\\沙箱仓库2\\.obsidian\\plugins\\obsidian-flow-form";

// 确定输出目录：生产模式直接输出到 Obsidian 插件目录，开发模式输出到当前目录
const OUTPUT_DIR = prod ? OBSIDIAN_PLUGIN_DIR : ".";

const cssOutputPlugin = () => ({
	name: "css-output-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			const file = build.initialOptions.outfile;
			// rename css file
			const parent = path.dirname(file);
			const cssFileName = path.join(parent, "main.css");
			const newCssFileName = path.join(parent, "styles.css");
			
			try {
				if (fs.existsSync(cssFileName)) {
					fs.renameSync(cssFileName, newCssFileName);
					console.log(`✅ 已重命名 CSS 文件: ${newCssFileName}`);
				}
				
				// 生产模式：复制 manifest.json 到输出目录
				if (prod) {
					const manifestSource = "manifest.json";
					const manifestTarget = path.join(parent, "manifest.json");
					if (fs.existsSync(manifestSource)) {
						fs.copyFileSync(manifestSource, manifestTarget);
						console.log(`✅ 已复制 manifest.json 到: ${manifestTarget}`);
					}
					
					console.log(`\n🎉 插件文件已直接构建到 Obsidian 目录: ${OBSIDIAN_PLUGIN_DIR}`);
				}
			} catch (e) {
				console.error("❌ CSS 处理失败:", e);
			}
		});
	},
});

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [cssOutputPlugin()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(OUTPUT_DIR, "main.js"),
	minify: prod,
});

// 生产模式：确保输出目录存在
if (prod && !fs.existsSync(OUTPUT_DIR)) {
	fs.mkdirSync(OUTPUT_DIR, { recursive: true });
	console.log(`📁 创建输出目录: ${OUTPUT_DIR}`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
