import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs'
import path from 'path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

// Obsidian 插件目标目录
const OBSIDIAN_PLUGIN_DIR = 'C:\\Desktop\\沙箱仓库2\\.obsidian\\plugins\\tars'

// 复制文件到 Obsidian 插件目录的插件
const copyToObsidianPlugin = () => ({
	name: 'copy-to-obsidian',
	setup(build) {
		build.onEnd(async (result) => {
			if (!prod) return
			
			try {
				// 确保目标目录存在
				if (!fs.existsSync(OBSIDIAN_PLUGIN_DIR)) {
					fs.mkdirSync(OBSIDIAN_PLUGIN_DIR, { recursive: true })
					console.log(`创建目标目录: ${OBSIDIAN_PLUGIN_DIR}`)
				}
				
				const currentDir = process.cwd()
				
				// 复制 main.js
				const mainJsSource = path.join(currentDir, 'main.js')
				const mainJsTarget = path.join(OBSIDIAN_PLUGIN_DIR, 'main.js')
				if (fs.existsSync(mainJsSource)) {
					fs.copyFileSync(mainJsSource, mainJsTarget)
					console.log(`已复制 main.js 到: ${mainJsTarget}`)
				}
				
				// 复制 styles.css
				const stylesSource = path.join(currentDir, 'styles.css')
				const stylesTarget = path.join(OBSIDIAN_PLUGIN_DIR, 'styles.css')
				if (fs.existsSync(stylesSource)) {
					fs.copyFileSync(stylesSource, stylesTarget)
					console.log(`已复制 styles.css 到: ${stylesTarget}`)
				}
				
				// 复制 manifest.json
				const manifestSource = path.join(currentDir, 'manifest.json')
				const manifestTarget = path.join(OBSIDIAN_PLUGIN_DIR, 'manifest.json')
				if (fs.existsSync(manifestSource)) {
					fs.copyFileSync(manifestSource, manifestTarget)
					console.log(`已复制 manifest.json 到: ${manifestTarget}`)
				}
				
				console.log(`✅ Tars 插件文件已成功部署到 Obsidian 目录！`)
			} catch (e) {
				console.error('复制文件失败:', e)
			}
		})
	}
})

const context = await esbuild.context({
	banner: {
		js: banner
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [copyToObsidianPlugin()],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
